Portfolio second part
denigit5/Portfolio pull request #2
Opened 2023-04-28 20:01 UTC by denigit5

This pull request adds new features to the Mobile first portfolio project.  Please review my changes and let me know if there's anything else I can do to improve this. Thank you!"

2023-04-28 20:35 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @denigit5, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

### README

- [x] 🚧 You did a great job documenting your project! 💯 However please make sure that you have a LICENSE and that its respective link in the README is working, you can follow these steps from [GitHub's official docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to set up a LICENSE. Microverse suggests using MIT! 🤓 🔧

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 20:35 UTC, anagudelogu commented on index.html
> +            <h2 class="card1-heading">Tonic</h2>
- [ ] You did a great job working on this milestone! 🚀 However, according to the requirements:

![image](https://user-images.githubusercontent.com/77069011/235246551-54821299-d54b-4fbd-a8d2-ffd0d194b39e.png)

The main container of your works section should use the `display: grid` CSS property, please consider using it! 🤓 🔧 

- [ ] Also, the contents of each project card should be aligned with `flexbox`, please consider using it too! 🤓 🔧

2023-04-28 20:35 UTC, anagudelogu commented on index.html
> +                </ul>
- [ ] This markup is semantically incorrect, lists, `<ul>` in this case, should have `<li>` elements as direct children instead of another element. Please consider updating your markup to meet this structure! 🤓 🔧 

```html
<ul>
  <li></li>
  <li></li>
  ...
</ul>
```

2023-04-28 20:35 UTC, anagudelogu commented on index.html
> +        <div class="connect2">LET'S CONNECT</div>
- [ ] Since this "LET'S CONNECT" acts as a title for your social media icons, it would be better to wrap it inside a `<hx>` tag, for example, `<h3>`. Please consider applying this! 🤓 🔧

2023-04-28 20:35 UTC, anagudelogu commented on index.html
> +          </li>
- [ ] I think that a better markup for this section would be using an "outer" list: (Languages, Frameworks, Skills), and inside each item of that list, there's another one listing its contents, something like this:

```html
<ul>
  <li>
    <h4>Languages</h4>
    <ul>
      <li>JavaScript</li>
      <li>Ruby</li>
      <li>HTML</li>
      <li>CSS</li>
    </ul>
  </li>
  <li>
    <h4>Frameworks</h4>
    ...
  </li>
  <li>
    <h4>Skills</h4>
    ...
  </li>
</ul>
```

Please consider applying this change! 🤓 🔧

2023-04-28 20:35 UTC, anagudelogu commented on index.html
> +            <button class="see-project">See project</button>
- [ ] According to the requirements:

![image](https://user-images.githubusercontent.com/77069011/235249061-26251fb7-3f8f-4e05-9f33-23266a3921fe.png)

Please consider implementing the button interaction effects for all the buttons in your portfolio! 🤓 🔧 

![image](https://user-images.githubusercontent.com/77069011/235249176-a4243f88-ad3c-4347-951c-fae2253d0aa2.png)

2023-04-28 20:35 UTC, anagudelogu commented on index.html
> +        <button class="see-project">Get my resume</button>
- [ ] The same happens here, please consider implementing the button interaction effects for all the buttons in your portfolio! 🤓 🔧 

![image](https://user-images.githubusercontent.com/77069011/235249176-a4243f88-ad3c-4347-951c-fae2253d0aa2.png)

2023-04-28 20:35 UTC, anagudelogu commented on style.css
> +  }
- [ ] I noticed that you have multiple repeated CSS properties across your stylesheet. It would be great if you can find a way of reducing this duplication of code ♻️. Remember that not repeating pieces of code will keep your codebase clean and readable. 🤓 🛠️

From [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md):
![image](https://user-images.githubusercontent.com/77069011/200000947-9e58c4d8-fed4-45f8-a822-7828c6e713f7.png)

In this case, you could do this with flex:

```CSS
.flex {
  display: flex;
}
```

And then, use it in your HTML elements where you need a flex container:

```HTML
<div class="flex"> This is a flex container </div>
```

Please, consider fixing this! 🤓

2023-04-29 14:28 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @denigit5 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️ Descriptions are  descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 14:28 UTC, abdulhamiid commented on index.html
> +          </li>
As requested by the previous reviewer, and according to the project requirement, Please let's use `ul` and `li` for categories in the "About myself" section. `Languages`, `Frameworks`, and `Skills` should be list items. 💪🛠

Requirement screenshot 👇 

![image](https://user-images.githubusercontent.com/78251927/235299374-9746bbab-bbf9-4af9-b124-51b8a57b6dd2.png)

2023-04-29 14:28 UTC, abdulhamiid commented on style.css
> +    pointer-events: none;
As requested by the previous reviewer, It would be great if you can find a way of reducing duplication of code ♻️ to follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

Remember that not repeating pieces of code will keep your codebase clean and readable. 🤓 🛠️

As requested by the previous reviewer, It would be great if you can find a way of reducing duplication of code ♻️ to follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

Remember that not repeating pieces of code will keep your codebase clean and readable. 🤓 🛠️

If you want to create a CSS rule for multiple elements, let's use a class attribute instead. For example, instead of repeating code 3 or more times

you can create a class and add it to all elements that need that style.

```CSS
.button {
  display: flex;
  flex-direction: row;
  align-items: center;
  list-style: none;
  padding: 4px 12px;
  width: 49px;
  height: 24px;
  background: #ebebff;
  border-radius: 8px;
  border: 0;
  color: rgba(96, 112, 255, 1);
}
```
```HTML
<button class"button">See Project</button>
```
Please kindly fix this  👍

2023-04-29 14:28 UTC, abdulhamiid commented on style.css
> +  }
As requested by the previous reviewer,  It would be great if you can find a way of reducing the duplication of the CSS `flex` property to follow the best practice. 

Please kindly check the previous reviewer's comment on that. 👍  🤗

2023-04-29 16:38 UTC, denigit5 commented on index.html
> +          </li>
Hello. should I remove the button attribute from the lists?

2023-04-30 03:57 UTC, denigit5 commented on style.css
> +  }
Thank you for the proposed changes but hovering over buttons without clicking is not applicable on mobile screen devices. Let me know what you think.

2023-05-01 16:19 UTC, denigit5 commented
Does the hover property work on mobile screen without Clicking by just the pointer navigating on them?

2023-05-01 17:18 UTC, vickymarz requested changes
Hi @denigit5, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Good UI design✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 17:18 UTC, vickymarz commented on index.html
> +            <h4 class="languages">Languages</h4>
- [ ] Good job so far 👍🏽 . Kindly ensure that your language category is also wrapped in a <li> tag just as you did for the skills and framework category 👍🏽

2023-05-01 17:18 UTC, vickymarz commented on index.html
> +    </section>
- [ ] The project requirement didn't specify that you should implement the contact section. I think it will be better if you stick to the project requirements and the milestones. This way you will have more time to work on each milestone properly and also get quality code reviews  😄

2023-05-01 17:18 UTC, vickymarz commented on index.html
> +                    <li><button class="tag tag3"><a href=""></a> CSS</button></li>
- [ ] Kindly reduce the gap between your languages ad their respective images so that they can match the figma design

your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/235494609-213edd37-b9ed-4bf5-994c-ac0473d7312d.png)

figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/235494574-62ff1dca-edd5-4e09-a9da-eef6cf1cef51.png)

2023-05-01 17:18 UTC, vickymarz commented on index.html
> +                    <li><button class="tag tag1"></a> Javascript</button></li>
- [ ] Kindly remove the closing anchor `<a>` tag you added here. I guess it was an oversight

2023-05-01 17:18 UTC, vickymarz commented on index.html
> +            <h4 class="languages">Languages</h4>
- [ ] Kindly add the arrow down icon for the language category title just like you did for the skills and framework title

your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/235495352-5015b926-819a-4cba-ad56-711c4482c966.png)

figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/235495439-e1feefdf-1cb1-4681-be59-5b1f80d68690.png)

2023-05-02 07:49 UTC, skyv26 approved these changes
## Hi @denigit5, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/5PKQrJbDKMnxUeqgvT/giphy.gif)

## Highlights
- Good UI design ✅ 
- Linters are passing ✅ 
- Used correct `GitHub` flow ✅ 
- Implemented the requirements ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 13:13 UTC, merged